version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ptarmigan"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kd9cibuz1ynw"
s3_prefix = "ptarmigan"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
