Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 35
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /home/reinier/Documents/GitHub/Ptarmigan/backend/sam/GetSentimentHistoryGraph/hello_world
      Runtime: python3.8