Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.comprehendTweetHandler
      CodeUri: /home/reinier/Documents/GitHub/Ptarmigan/backend/sam/comprehend/comprehend
      Runtime: python3.8