Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /home/reinier/Documents/GitHub/Ptarmigan/backend/sam/comprehend/comprehend
      Runtime: python3.8