/*// Mocks generated by Mockito 5.0.9 from annotations
// in ptarmigan/test/main_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
//import 'package:ptarmigan/main.dart' as _i2;
import 'package:ptarmigan/models/Feed.dart' as _i3;
import 'package:ptarmigan/services/feed_changer.dart' as i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FeedChanger].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedChanger extends _i1.Mock implements _i2.FeedChanger {}

/// A class which mocks [Subscriber].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriber extends _i1.Mock implements _i2.Subscriber {}

/// A class which mocks [Feed].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockFeed extends _i1.Mock implements _i3.Feed {}
*/